"""create_chain_tables

Revision ID: 66205739abcd
Revises: ae3459876543
Create Date: 2026-01-21 13:40:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66205739abcd'
down_revision = 'ae3459876543'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chains',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('category', sa.String(length=255), nullable=True),
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
        sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('execution_count', sa.Integer(), nullable=False),
        sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chains_category'), 'chains', ['category'], unique=False)
    op.create_index(op.f('ix_chains_name'), 'chains', ['name'], unique=False)
    op.create_index(op.f('ix_chains_status'), 'chains', ['status'], unique=False)

    op.create_table('chain_nodes',
        sa.Column('chain_id', sa.UUID(), nullable=False),
        sa.Column('node_id', sa.String(length=255), nullable=False),
        sa.Column('node_type', sa.String(length=50), nullable=False),
        sa.Column('agent_id', sa.UUID(), nullable=True),
        sa.Column('label', sa.String(length=255), nullable=False),
        sa.Column('position_x', sa.Float(), nullable=False),
        sa.Column('position_y', sa.Float(), nullable=False),
        sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
        sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_nodes_agent_id'), 'chain_nodes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_chain_nodes_chain_id'), 'chain_nodes', ['chain_id'], unique=False)
    op.create_index('idx_chain_node_unique', 'chain_nodes', ['chain_id', 'node_id'], unique=True)

    op.create_table('chain_edges',
        sa.Column('chain_id', sa.UUID(), nullable=False),
        sa.Column('edge_id', sa.String(length=255), nullable=False),
        sa.Column('source_node_id', sa.String(length=255), nullable=False),
        sa.Column('target_node_id', sa.String(length=255), nullable=False),
        sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('label', sa.String(length=255), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_edges_chain_id'), 'chain_edges', ['chain_id'], unique=False)
    op.create_index('idx_chain_edge_source', 'chain_edges', ['chain_id', 'source_node_id'], unique=False)
    op.create_index('idx_chain_edge_target', 'chain_edges', ['chain_id', 'target_node_id'], unique=False)
    op.create_index('idx_chain_edge_unique', 'chain_edges', ['chain_id', 'edge_id'], unique=True)

    op.create_table('chain_executions',
        sa.Column('chain_id', sa.UUID(), nullable=False),
        sa.Column('execution_name', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('node_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('current_node_id', sa.String(length=255), nullable=True),
        sa.Column('completed_nodes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
        sa.Column('active_edges', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
        sa.Column('edge_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('triggered_by', sa.UUID(), nullable=True),
        sa.Column('correlation_id', sa.String(length=255), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_executions_chain_id'), 'chain_executions', ['chain_id'], unique=False)
    op.create_index(op.f('ix_chain_executions_correlation_id'), 'chain_executions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_chain_executions_current_node_id'), 'chain_executions', ['current_node_id'], unique=False)
    op.create_index(op.f('ix_chain_executions_started_at'), 'chain_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_chain_executions_status'), 'chain_executions', ['status'], unique=False)
    op.create_index(op.f('ix_chain_executions_triggered_by'), 'chain_executions', ['triggered_by'], unique=False)

    op.create_table('chain_execution_logs',
        sa.Column('execution_id', sa.UUID(), nullable=False),
        sa.Column('node_id', sa.String(length=255), nullable=True),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('level', sa.String(length=20), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['execution_id'], ['chain_executions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_execution_logs_execution_id'), 'chain_execution_logs', ['execution_id'], unique=False)
    op.create_index(op.f('ix_chain_execution_logs_timestamp'), 'chain_execution_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chain_execution_logs_timestamp'), table_name='chain_execution_logs')
    op.drop_index(op.f('ix_chain_execution_logs_execution_id'), table_name='chain_execution_logs')
    op.drop_table('chain_execution_logs')
    op.drop_index(op.f('ix_chain_executions_triggered_by'), table_name='chain_executions')
    op.drop_index(op.f('ix_chain_executions_status'), table_name='chain_executions')
    op.drop_index(op.f('ix_chain_executions_started_at'), table_name='chain_executions')
    op.drop_index(op.f('ix_chain_executions_current_node_id'), table_name='chain_executions')
    op.drop_index(op.f('ix_chain_executions_correlation_id'), table_name='chain_executions')
    op.drop_index(op.f('ix_chain_executions_chain_id'), table_name='chain_executions')
    op.drop_table('chain_executions')
    op.drop_index('idx_chain_edge_unique', table_name='chain_edges')
    op.drop_index('idx_chain_edge_target', table_name='chain_edges')
    op.drop_index('idx_chain_edge_source', table_name='chain_edges')
    op.drop_index(op.f('ix_chain_edges_chain_id'), table_name='chain_edges')
    op.drop_table('chain_edges')
    op.drop_index('idx_chain_node_unique', table_name='chain_nodes')
    op.drop_index(op.f('ix_chain_nodes_chain_id'), table_name='chain_nodes')
    op.drop_index(op.f('ix_chain_nodes_agent_id'), table_name='chain_nodes')
    op.drop_table('chain_nodes')
    op.drop_index(op.f('ix_chains_status'), table_name='chains')
    op.drop_index(op.f('ix_chains_name'), table_name='chains')
    op.drop_index(op.f('ix_chains_category'), table_name='chains')
    op.drop_table('chains')
    # ### end Alembic commands ###
