"""Add RAG tables

Revision ID: 92821eb50fcb
Revises: 9cf1246ff13d
Create Date: 2026-01-21 15:23:31.167714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92821eb50fcb'
down_revision = '9cf1246ff13d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('content_source', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_sources_owner_id'), 'rag_sources', ['owner_id'], unique=False)
    op.create_table('agent_rag_sources',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('rag_source_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['rag_source_id'], ['rag_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_rag_sources_agent_id'), 'agent_rag_sources', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_rag_sources_rag_source_id'), 'agent_rag_sources', ['rag_source_id'], unique=False)
    op.alter_column('chat_messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_chat_messages_id', table_name='chat_messages')
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chat_sessions', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_sessions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_chat_sessions_id', table_name='chat_sessions')
    op.drop_constraint('chat_sessions_chain_id_fkey', 'chat_sessions', type_='foreignkey')
    op.drop_constraint('chat_sessions_user_id_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'chains', ['chain_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mcp_servers', 'env_vars',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('mcp_servers', 'protocol',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('mcp_servers', 'resources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('mcp_servers', 'prompts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('mcp_servers', 'server_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_servers', 'server_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('mcp_servers', 'prompts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               nullable=True)
    op.alter_column('mcp_servers', 'resources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               nullable=True)
    op.alter_column('mcp_servers', 'protocol',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'websocket'::character varying"),
               nullable=True)
    op.alter_column('mcp_servers', 'env_vars',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_user_id_fkey', 'chat_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('chat_sessions_chain_id_fkey', 'chat_sessions', 'chains', ['chain_id'], ['id'])
    op.create_index('ix_chat_sessions_id', 'chat_sessions', ['id'], unique=False)
    op.alter_column('chat_sessions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.create_index('ix_chat_messages_id', 'chat_messages', ['id'], unique=False)
    op.alter_column('chat_messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_rag_sources_rag_source_id'), table_name='agent_rag_sources')
    op.drop_index(op.f('ix_agent_rag_sources_agent_id'), table_name='agent_rag_sources')
    op.drop_table('agent_rag_sources')
    op.drop_index(op.f('ix_rag_sources_owner_id'), table_name='rag_sources')
    op.drop_table('rag_sources')
    # ### end Alembic commands ###