"""Add RAG tables for knowledge base

Revision ID: afa6dbcedbc4
Revises: 92821eb50fcb
Create Date: 2026-01-21 15:56:02.799994

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql


# revision identifiers, used by Alembic.
revision = 'afa6dbcedbc4'
down_revision = '92821eb50fcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables already exist (they were auto-created by SQLAlchemy)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Create rag_sources table only if it doesn't exist
    if 'rag_sources' not in existing_tables:
        op.create_table('rag_sources',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('source_type', sa.String(length=50), nullable=False),
        sa.Column('content_source', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('owner_id', sa.UUID(), nullable=False),
        sa.Column('processing_metadata', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_rag_sources_owner_id'), 'rag_sources', ['owner_id'], unique=False)
    
    # Create agent_rag_sources table only if it doesn't exist
    if 'agent_rag_sources' not in existing_tables:
        op.create_table('agent_rag_sources',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('agent_id', sa.UUID(), nullable=False),
        sa.Column('rag_source_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
        sa.ForeignKeyConstraint(['rag_source_id'], ['rag_sources.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_agent_rag_sources_agent_id'), 'agent_rag_sources', ['agent_id'], unique=False)
        op.create_index(op.f('ix_agent_rag_sources_rag_source_id'), 'agent_rag_sources', ['rag_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_rag_sources_rag_source_id'), table_name='agent_rag_sources')
    op.drop_index(op.f('ix_agent_rag_sources_agent_id'), table_name='agent_rag_sources')
    op.drop_table('agent_rag_sources')
    op.drop_index(op.f('ix_rag_sources_owner_id'), table_name='rag_sources')
    op.drop_table('rag_sources')
    # ### end Alembic commands ###