# Custom Ollama Docker Image
# Extends the official Ollama image (https://github.com/ollama/ollama)
# Ollama is licensed under the MIT License - Copyright (c) Ollama
# See deployment/LICENSES/OLLAMA-LICENSE for full license text
FROM ollama/ollama:latest


# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Use the entrypoint script to start Ollama and pull models
ENTRYPOINT ["/entrypoint.sh"]